In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

# Random Agent

In [3]:
from agent import RandomAgent

In [4]:
ra = RandomAgent(stochastic=True)
ra.run(n_iter=1, show_board=True)

[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['*' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['*' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['*' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '*' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '*' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '*' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '*' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '*' 'LOSE']
 ['0' '0'

[-1]

In [5]:
hist = ra.run(n_iter=10000, show_board=False)
print('Random Agent success rate:', np.mean(np.array(hist) == 1))

Random Agent success rate: 0.2873


# Monte Carlo Method for Unknown Dynamics

In [6]:
from agent import MCAgent

mc = MCAgent(stochastic=True)
mc.train()

c:\Users\hlee2\문서\Reinforcement Learning\Grid World\agent.py:77: RuntimeWarning: invalid value encountered in divide
  mean_av_func = np.where(count == 0, 0, cum_av_func / count)


iteration: 1
old action-value function: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
updated action-value function: [[ 0.05444186 -0.0208044   0.11868541  0.03872383]
 [ 0.12614381  0.10720687  0.24323675  0.04738743]
 [ 0.27838963 -0.36520816  1.          0.11728022]
 [ 0.          0.          0.          0.        ]
 [ 0.02893254 -0.07699582 -0.01891004 -0.01573819]
 [ 0.          0.          0.          0.        ]
 [ 0.04589476 -0.28808225 -1.         -0.36375148]
 [ 0.          0.          0.          0.        ]
 [-0.03794446 -0.07755972 -0.14804681 -0.0798279 ]
 [-0.15358803 -0.15066942 -0.28203959 -0.07647416]
 [-0.34488632 -0.27649574 -0.47407171 -0.15193044]
 [-0.8791081  -0.47986359 -0.4767659  -0.28333656]]
[[False  True False  True]
 [False False False  True]
 [False False False False]
 [ True  True  True  True]
 [ True False  True  True]


In [7]:
mc.run(n_iter=1, eps=0, show_board=True)

[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['*' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['*' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '*' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '*' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' '*']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------


([1],
 [deque([((2, 0), 'North', 0),
         ((2, 0), 'North', 0),
         ((1, 0), 'North', 0),
         ((1, 0), 'North', 0),
         ((1, 0), 'North', 0),
         ((0, 0), 'East', 0),
         ((0, 1), 'East', 0),
         ((0, 2), 'East', 1)])])

In [8]:
hist, _ = mc.run(n_iter=10000, eps=0, show_board=False)     # run with greedy algorithm(eps=0) after finding optimal a-v function
print('Monte Carlo Agent success rate:', np.mean(np.array(hist) == 1))

Monte Carlo Agent success rate: 1.0
