In [1]:
%load_ext autoreload
%autoreload 2

In [11]:
import numpy as np
from agent import RandomAgent, MCAgent

# Random Agent

In [15]:
ra = RandomAgent(stochastic=True)
ra.run(n_iter=1, show_board=True)

[['0' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['*' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['*' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0'

[-1]

In [17]:
hist = ra.run(n_iter=10000, show_board=False)
print('Random Agent success rate:', np.mean(np.array(hist) == 1))

Random Agent success rate: 0.2866


# Monte Carlo Method

In [9]:
from agent import MCAgent

mc = MCAgent(stochastic=False)
mc.train()

c:\Users\hlee2\문서\Reinforcement Learning\Grid World\agent.py:77: RuntimeWarning: invalid value encountered in divide
  print(cum_av_func)


iteration: 1
old action-value function: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
updated action-value function: [[ 0.05703011 -0.01328431  0.13140662  0.04751341]
 [ 0.1329982   0.13037539  0.25786189  0.04623944]
 [ 0.31485504 -0.34181055  1.          0.12795916]
 [ 0.          0.          0.          0.        ]
 [ 0.03942887 -0.07444959 -0.01856405 -0.01338937]
 [ 0.          0.          0.          0.        ]
 [ 0.06702805 -0.27873463 -1.         -0.34241578]
 [ 0.          0.          0.          0.        ]
 [-0.03251676 -0.07305977 -0.14392788 -0.07675854]
 [-0.15051063 -0.14806228 -0.27533364 -0.07291811]
 [-0.33877267 -0.27804381 -0.46531799 -0.14813599]
 [-0.87516976 -0.47945327 -0.47009526 -0.28884667]]
[[False  True False  True]
 [False False False  True]
 [False False False False]
 [ True  True  True  True]
 [ True False  True  True]


In [13]:
mc.run(n_iter=1, eps=0, show_board=True)

[['0' '0' '0' 'WIN']
 ['*' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['*' '0' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '*' '0' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '*' 'WIN']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------
[['0' '0' '0' '*']
 ['0' 'BLOCK' '0' 'LOSE']
 ['0' '0' '0' '0']]
--------------------------------------------------


([1],
 [deque([((2, 0), 'North', 0),
         ((1, 0), 'North', 0),
         ((0, 0), 'East', 0),
         ((0, 1), 'East', 0),
         ((0, 2), 'East', 1)])])

In [12]:
hist, _ = mc.run(n_iter=10000, eps=0, show_board=False)
print('Monte Carlo Agent success rate:', np.mean(np.array(hist) == 1))

Monte Carlo success rate: 1.0
